spring:
  profiles:
    active: pie


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    root: INFO
    org.springframework.messaging.simp: DEBUG

springfox:
  documentation:
    swagger-ui:
      enabled: true

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#  default-consumes-media-type: application/json; charset=UTF-8
#  default-produces-media-type: application/json; charset=UTF-8

